/**
 * Created by Drew on 12/30/2014.
 */

module.exports = {
    ADD_ITEM: 'ADD_ITEM',
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',

    DELETE_ITEM: 'DELETE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',

    LOAD_ITEMS: 'LOAD_ITEMS',
    LOAD_ITEMS_SUCCESS: 'LOAD_ITEMS_SUCCESS',
    LOAD_ITEMS_FAILURE: 'LOAD_ITEMS_FAILURE'
};